### ISSUE TITLE
Integer values should not output a decimal point

### ISSUE THREAD

**Issue by moleike** [moleike/jsonnet-hs#3]
When Jsonnet numbers are integers we should avoid (pretty)printing the decimal point. So we should first determine if the number is floating point or integer in the `manifestation` stage.

Bonus points: change the representation of numbers from `Double` to `Data.Scientific`. See: https://hackage.haskell.org/package/megaparsec-9.0.0/docs/Text-Megaparsec-Char-Lexer.html#g:4

Join our gitter [channel](https://gitter.im/jsonnet-haskell/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link) if you have further questions or need help!

**Comment by zuliatowoade** [comment]
@moleike I will like to work this issue. Do you mind assigning it to me?

**Comment by zuliatowoade** [comment]
@moleike  I sent a message on the channel you provide but haven't heard back so I am deciding to send it over here as well. 

I noticed the main.hs module just has a dummy function. Would you mind providing steps on how you are currently running the application? Are you directly just calling the classes/functions?
Also, I went through the code stack and from my understanding, this issue should involve adding a new parameter e.g VInt, and in the manifest function connect it to a corresponding JInt variable which will be used in printing integers when called from the pretty function. Let me know if I am on the right track. Thank you!

**Comment by moleike** [comment]
Hi @zuliatowoade! My bad, didn't get notified of gitter messages.

**Comment by moleike** [comment]
@zuliatowoade I replied your messages in the chatroom. I will try to be more active there these days in gitter 😃

**Comment by moleike** [comment]
solved in f2bfff146a9f5f0e3cc71b5457d1ef25a2cf3b32
